name: CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  install_dependencies:
    runs-on: gmrx-vesting-runner
    # Perform NPM install
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
